name: Argo
on:
  push:
    branches:
      - argo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install k3s
        run: curl -sfL https://get.k3s.io | sh -
      - run: sudo k3s server &
      - run: sudo k3s kubectl get nodes
